import "./jsonSchemaToZod.test.js";
import "./eval.test.js";
import "./parsers/parseAnyOf.test.js";
import "./parsers/parseConst.test.js";
import "./parsers/parseNot.test.js";
import "./parsers/parseNumber.test.js";
import "./parsers/parseObject.test.js";
import "./parsers/parseOneOf.test.js";
import "./parsers/parseSchema.test.js";
import "./parsers/parseString.test.js";
import "./utils/cliTools.test.js";
import "./utils/omit.test.js";
import "./utils/half.test.js";
import "./parsers/parseNullable.test.js"
